version: '3.8'

services:
  intg-test-server:
    container_name: intg-test-server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mongodb://mongo:27017/
  mongo:
    restart: always
    image: mongo:4.2.0
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s