version: '3.7'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    environment:
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - '3000:3000'
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s