version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - DBHOST=mongodb://mongo:27017/
    ports:
      - '4000:4000'
    networks:
      - node-webapp-network
  mongo:
    restart: always
    image: mongo:4.2.0
    container_name: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge