name: deploy

on:
  # the 1st condition
  workflow_run:
    workflows: ["ci"]
    branches: ["main"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2
env:
    DBHOST: ${{ secrets.DBHOST }}
    IMAGE_NAME: ${{ github.event.repository.name }}

jobs:   
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},DBHOST
          script: |
            # Login to registry
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # Stop and remove running container
            docker stop $(echo $IMAGE_NAME)
            docker rm $(echo $IMAGE_NAME)
            # Run a new container from a new image
            docker run -d --pull always --restart always --name $(echo $IMAGE_NAME) -e DBHOST=$(echo $DBHOST) -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest